apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mezz51gzj-nodejs
  janus-idp.io/tekton: mezz51gzj-nodejs
  backstage.io/kubernetes-id: mezz51gzj-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mezz51gzj-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
