apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mezz51gzj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mezz51gzj-nodejs 
  name: mezz51gzj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mezz51gzj-nodejs 
